package lexer

var keywords = map[string]struct{}{
	"if":        {},
	"else":      {},
	"func":      {},
	"extern":    {},
	"return":    {},
	"type":      {},
	"table":     {},
	"var":       {},
	"const":     {},
	"package":   {},
	"pragma":    {},
	"for":       {},
	"break":     {},
	"continue":  {},
	"import":    {},
	"true":      {},
	"false":     {},
	"interface": {},
	"range":     {},
	"make":		 {},
	"panic":	 {},
}
